1747295646.3378565 [INFO] [launch]: All log files can be found below /home/stas/KNR/Dron_symulacja/mission_lig/2025-05-15-09-54-06-337091-stas-Legion-Y540-15IRH-PG0-11622
1747295646.3379884 [INFO] [launch]: Default logging verbosity is set to INFO
1747295646.3931580 [INFO] [drone_handler-1]: process started with pid [11623]
1747295646.3933907 [INFO] [camera_node-2]: process started with pid [11625]
1747295646.3935411 [INFO] [images_recorder-3]: process started with pid [11627]
1747295646.3937027 [INFO] [aruco_node-4]: process started with pid [11629]
1747295646.3938563 [INFO] [ros_mission_website-5]: process started with pid [11631]
1747295646.5852532 [camera_node-2] [0:47:13.696473272] [11625] [1;32m INFO [1;37mCamera [1;34mcamera_manager.cpp:284 [0mlibcamera v0.1.0
1747295646.6838791 [camera_node-2] [0m[INFO] [1747295646.683551632] [camera]: 
1747295646.6844702 [camera_node-2] >> cameras:
1747295646.6850805 [camera_node-2]    0: Integrated Camera: Integrated C (\_SB_.PCI0.XHC_.RHUB.HS06-6:1.0-5986:2113)[0m
1747295646.6855111 [camera_node-2] [33m[WARN] [1747295646.683723496] [camera]: no camera selected, using default: "\_SB_.PCI0.XHC_.RHUB.HS06-6:1.0-5986:2113"[0m
1747295646.6867635 [camera_node-2] [33m[WARN] [1747295646.683760680] [camera]: set parameter 'camera' to silence this warning[0m
1747295646.6974232 [camera_node-2] [0m[INFO] [1747295646.696824533] [camera]: 
1747295646.6978550 [camera_node-2] >> stream formats:
1747295646.6980257 [camera_node-2]    - MJPEG (320x180 - 1280x720)
1747295646.6984029 [camera_node-2]    - YUYV (320x180 - 1280x720)[0m
1747295646.6988389 [camera_node-2] terminate called after throwing an instance of 'std::runtime_error'
1747295646.6995037 [camera_node-2]   what():  unsupported pixel format "RGB888"
1747295647.2087345 [aruco_node-4] [0m[INFO] [1747295647.208438265] [aruco_node]: Marker size: 0.1[0m
1747295647.2094965 [aruco_node-4] [0m[INFO] [1747295647.209309998] [aruco_node]: Marker type: DICT_4X4_100[0m
1747295647.2101040 [aruco_node-4] [0m[INFO] [1747295647.209936744] [aruco_node]: Image topic: camera/image_raw[0m
1747295647.2109609 [aruco_node-4] [0m[INFO] [1747295647.210791331] [aruco_node]: Intrinsic matrix: [[  1.   0. 320.]
1747295647.2110891 [aruco_node-4]  [  0.   1. 240.]
1747295647.2111926 [aruco_node-4]  [  0.   0.   1.]][0m
1747295647.2117095 [aruco_node-4] [0m[INFO] [1747295647.211531403] [aruco_node]: Distortion: [0. 0. 0. 0.][0m
1747295647.2473664 [images_recorder-3] [0m[INFO] [1747295647.247098309] [images_recorder]: camera_topic: camera/image_raw[0m
1747295647.2834773 [images_recorder-3] [0m[INFO] [1747295647.283214364] [images_recorder]: Saving images to saved_images/6[0m
1747295647.2840724 [images_recorder-3] [0m[INFO] [1747295647.283923749] [images_recorder]: video_recorder node created[0m
1747295647.2846181 [images_recorder-3] [0m[INFO] [1747295647.284496322] [images_recorder]: Recording images to directory: saved_images/6[0m
1747295647.3454030 [drone_handler-1] [33m[WARN] [1747295647.345137415] [drone_handler]: DEV MODE is enabled.[0m
1747295647.3456948 [drone_handler-1] [0m[INFO] [1747295647.345525619] [drone_handler]: Connecting with copter at /dev/ttyACM0...[0m
1747295647.3479064 [drone_handler-1] [31m[ERROR] [1747295647.347730179] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'[0m
1747295647.3482945 [drone_handler-1] [0m[INFO] [1747295647.348092157] [drone_handler]: Retrying to connect in {3} seconds...[0m
1747295647.4583700 [ros_mission_website-5] [0m[INFO] [1747295647.458150908] [ros_mission_website]: MissionWebsiteClient node created[0m
1747295647.8813698 [ERROR] [camera_node-2]: process has died [pid 11625, exit code -6, cmd '/opt/ros/humble/lib/camera_ros/camera_node --ros-args --params-file /tmp/launch_params_we79_1of'].
1747295647.9296534 [ros_mission_website-5] [0m[INFO] [1747295647.929371258] [ros_mission_website]: âœ… Server is available.[0m
1747295648.2847962 [images_recorder-3] [33m[WARN] [1747295648.284554854] [images_recorder]: No frame to save yet[0m
1747295648.4527755 [ros_mission_website-5] [0m[INFO] [1747295648.452559612] [ros_mission_website]: Status telemetry post: 200[0m
1747295649.0151060 [ros_mission_website-5] [0m[INFO] [1747295649.014893102] [ros_mission_website]: Status telemetry post: 200[0m
1747295649.2846677 [images_recorder-3] [33m[WARN] [1747295649.284412039] [images_recorder]: No frame to save yet[0m
1747295649.4769440 [ros_mission_website-5] [0m[INFO] [1747295649.476727430] [ros_mission_website]: Status telemetry post: 200[0m
1747295650.0695057 [ros_mission_website-5] [0m[INFO] [1747295650.069268778] [ros_mission_website]: Status telemetry post: 200[0m
1747295650.2842150 [images_recorder-3] [33m[WARN] [1747295650.283995575] [images_recorder]: No frame to save yet[0m
1747295650.3521295 [drone_handler-1] [31m[ERROR] [1747295650.351887633] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'[0m
1747295650.3524420 [drone_handler-1] [0m[INFO] [1747295650.352275867] [drone_handler]: Retrying to connect in {3} seconds...[0m
1747295650.5947933 [ros_mission_website-5] [0m[INFO] [1747295650.594578921] [ros_mission_website]: Status telemetry post: 200[0m
1747295651.1916435 [ros_mission_website-5] [0m[INFO] [1747295651.191427301] [ros_mission_website]: Status telemetry post: 200[0m
1747295651.2848763 [images_recorder-3] [33m[WARN] [1747295651.284637230] [images_recorder]: No frame to save yet[0m
1747295651.8078165 [ros_mission_website-5] [0m[INFO] [1747295651.807596234] [ros_mission_website]: Status telemetry post: 200[0m
1747295652.2847080 [images_recorder-3] [33m[WARN] [1747295652.284466861] [images_recorder]: No frame to save yet[0m
1747295652.4237921 [ros_mission_website-5] [0m[INFO] [1747295652.423578631] [ros_mission_website]: Status telemetry post: 200[0m
1747295652.9115820 [ros_mission_website-5] [0m[INFO] [1747295652.911321311] [ros_mission_website]: Status telemetry post: 200[0m
1747295653.2849004 [images_recorder-3] [33m[WARN] [1747295653.284662168] [images_recorder]: No frame to save yet[0m
1747295653.3554275 [drone_handler-1] [31m[ERROR] [1747295653.355180652] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'[0m
1747295653.3558788 [drone_handler-1] [0m[INFO] [1747295653.355658133] [drone_handler]: Retrying to connect in {3} seconds...[0m
1747295653.4475453 [ros_mission_website-5] [0m[INFO] [1747295653.447287524] [ros_mission_website]: Status telemetry post: 200[0m
1747295653.9219236 [ros_mission_website-5] [0m[INFO] [1747295653.921692780] [ros_mission_website]: Status telemetry post: 200[0m
1747295654.2844210 [images_recorder-3] [33m[WARN] [1747295654.284183444] [images_recorder]: No frame to save yet[0m
1747295654.5686564 [ros_mission_website-5] [0m[INFO] [1747295654.568403550] [ros_mission_website]: Status telemetry post: 200[0m
1747295655.1834397 [ros_mission_website-5] [0m[INFO] [1747295655.183226659] [ros_mission_website]: Status telemetry post: 200[0m
1747295655.2841709 [images_recorder-3] [33m[WARN] [1747295655.283932304] [images_recorder]: No frame to save yet[0m
1747295655.7954333 [ros_mission_website-5] [0m[INFO] [1747295655.795218609] [ros_mission_website]: Status telemetry post: 200[0m
1747295656.2848768 [images_recorder-3] [33m[WARN] [1747295656.284641243] [images_recorder]: No frame to save yet[0m
1747295656.3598485 [drone_handler-1] [31m[ERROR] [1747295656.359606709] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'[0m
1747295656.3602509 [drone_handler-1] [0m[INFO] [1747295656.359998241] [drone_handler]: Retrying to connect in {3} seconds...[0m
1747295656.4134195 [ros_mission_website-5] [0m[INFO] [1747295656.413189254] [ros_mission_website]: Status telemetry post: 200[0m
1747295656.8912642 [ros_mission_website-5] [0m[INFO] [1747295656.891053452] [ros_mission_website]: Status telemetry post: 200[0m
1747295657.2842002 [images_recorder-3] [33m[WARN] [1747295657.283976724] [images_recorder]: No frame to save yet[0m
1747295657.4431484 [ros_mission_website-5] [0m[INFO] [1747295657.442932399] [ros_mission_website]: Status telemetry post: 200[0m
1747295658.0506599 [ros_mission_website-5] [0m[INFO] [1747295658.050409128] [ros_mission_website]: Status telemetry post: 200[0m
1747295658.2848749 [images_recorder-3] [33m[WARN] [1747295658.284638034] [images_recorder]: No frame to save yet[0m
1747295658.3954587 [INFO] [healthcheck-6]: process started with pid [11721]
1747295658.6641684 [ros_mission_website-5] [0m[INFO] [1747295658.663955329] [ros_mission_website]: Status telemetry post: 200[0m
1747295658.8221343 [healthcheck-6] [0m[INFO] [1747295658.821919316] [drone_healthcheck]: Checking drone_handler services...[0m
1747295659.2796206 [ros_mission_website-5] [0m[INFO] [1747295659.279362163] [ros_mission_website]: Status telemetry post: 200[0m
1747295659.2847130 [images_recorder-3] [33m[WARN] [1747295659.284571704] [images_recorder]: No frame to save yet[0m
1747295659.3634727 [drone_handler-1] [31m[ERROR] [1747295659.363190663] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'[0m
1747295659.3638997 [drone_handler-1] [0m[INFO] [1747295659.363644650] [drone_handler]: Retrying to connect in {3} seconds...[0m
1747295659.8160357 [ros_mission_website-5] [0m[INFO] [1747295659.815817404] [ros_mission_website]: Status telemetry post: 200[0m
1747295660.2848971 [images_recorder-3] [33m[WARN] [1747295660.284656516] [images_recorder]: No frame to save yet[0m
1747295660.4277246 [ros_mission_website-5] [0m[INFO] [1747295660.427511067] [ros_mission_website]: Status telemetry post: 200[0m
1747295660.9441829 [ros_mission_website-5] [0m[INFO] [1747295660.943965333] [ros_mission_website]: Status telemetry post: 200[0m
1747295661.2842612 [images_recorder-3] [33m[WARN] [1747295661.284022449] [images_recorder]: No frame to save yet[0m
1747295661.6316805 [ros_mission_website-5] [0m[INFO] [1747295661.631429573] [ros_mission_website]: Status telemetry post: 200[0m
1747295662.1432376 [ros_mission_website-5] [0m[INFO] [1747295662.143020174] [ros_mission_website]: Status telemetry post: 200[0m
1747295662.2809181 [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
1747295662.2848647 [drone_handler-1] Traceback (most recent call last):
1747295662.2850952 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
1747295662.2852185 [drone_handler-1]     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
1747295662.2853403 [drone_handler-1] FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295662.2854190 [drone_handler-1] 
1747295662.2855175 [drone_handler-1] During handling of the above exception, another exception occurred:
1747295662.2856097 [drone_handler-1] 
1747295662.2857037 [drone_handler-1] Traceback (most recent call last):
1747295662.2857816 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 83, in __init__
1747295662.2858751 [drone_handler-1]     self.vehicle = connect(connection_string, baud=57600, wait_ready=False)
1747295662.2859573 [drone_handler-1]   File "/usr/local/lib/python3.10/dist-packages/dronekit/__init__.py", line 3159, in connect
1747295662.2863860 [images_recorder-3] Traceback (most recent call last):
1747295662.2865350 [images_recorder-3]   File "/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/drone_camera/images_recorder", line 33, in <module>
1747295662.2866466 [images_recorder-3]     sys.exit(load_entry_point('drone-camera==0.0.0', 'console_scripts', 'images_recorder')())
1747295662.2867439 [images_recorder-3]   File "/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/python3.10/site-packages/drone_camera/images_recorder.py", line 66, in main
1747295662.2868302 [images_recorder-3]     rclpy.spin(images_recorder)
1747295662.2869248 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295662.2870226 [images_recorder-3]     executor.spin_once()
1747295662.2871206 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295662.2872109 [images_recorder-3]     self._spin_once_impl(timeout_sec)
1747295662.2873106 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
1747295662.2873862 [images_recorder-3]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
1747295662.2874703 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
1747295662.2875531 [images_recorder-3]     return next(self._cb_iter)
1747295662.2876289 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
1747295662.2877049 [images_recorder-3]     wait_set.wait(timeout_nsec)
1747295662.2877786 [images_recorder-3] KeyboardInterrupt
1747295662.2881384 [aruco_node-4] Traceback (most recent call last):
1747295662.2882605 [aruco_node-4]   File "/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/ros2_aruco/aruco_node", line 33, in <module>
1747295662.2883568 [aruco_node-4]     sys.exit(load_entry_point('ros2-aruco==0.1.0', 'console_scripts', 'aruco_node')())
1747295662.2884471 [aruco_node-4]   File "/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/python3.10/site-packages/ros2_aruco/aruco_node.py", line 193, in main
1747295662.2885578 [aruco_node-4]     rclpy.spin(node)
1747295662.2886460 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295662.2887328 [aruco_node-4]     executor.spin_once()
1747295662.2888212 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295662.2889075 [aruco_node-4]     self._spin_once_impl(timeout_sec)
1747295662.2889957 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
1747295662.2890842 [aruco_node-4]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
1747295662.2891734 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
1747295662.2892616 [aruco_node-4]     return next(self._cb_iter)
1747295662.2893448 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
1747295662.2894223 [aruco_node-4]     wait_set.wait(timeout_nsec)
1747295662.2895000 [aruco_node-4] KeyboardInterrupt
1747295662.2898448 [ros_mission_website-5] Traceback (most recent call last):
1747295662.2899384 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/drone_web/ros_mission_website", line 33, in <module>
1747295662.2900188 [ros_mission_website-5]     sys.exit(load_entry_point('drone-web==0.0.0', 'console_scripts', 'ros_mission_website')())
1747295662.2900922 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 142, in main
1747295662.2901642 [ros_mission_website-5]     rclpy.spin(mission_website_client)
1747295662.2902548 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295662.2903495 [ros_mission_website-5]     executor.spin_once()
1747295662.2904437 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295662.2905605 [ros_mission_website-5]     self._spin_once_impl(timeout_sec)
1747295662.2906632 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 746, in _spin_once_impl
1747295662.2907977 [ros_mission_website-5]     handler()
1747295662.2909236 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 254, in __call__
1747295662.2910156 [ros_mission_website-5]     self._handler.send(None)
1747295662.2911046 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 447, in handler
1747295662.2911921 [ros_mission_website-5]     await call_coroutine(entity, arg)
1747295662.2912791 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 361, in _execute_timer
1747295662.2913733 [ros_mission_website-5]     await await_or_execute(tmr.callback)
1747295662.2914488 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
1747295662.2915437 [ros_mission_website-5]     return callback(*args)
1747295662.2916198 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 112, in post_all_to_server
1747295662.2917004 [ros_mission_website-5]     self.post_telemetry_to_server()
1747295662.2917752 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 105, in post_telemetry_to_server
1747295662.2918546 [ros_mission_website-5]     response = requests.post(f"{self.web_app_base_url}/api/status", json=self.current_telemetry)
1747295662.2919352 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
1747295662.2920144 [ros_mission_website-5]     return request('post', url, data=data, json=json, **kwargs)
1747295662.2920969 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
1747295662.2921779 [ros_mission_website-5]     return session.request(method=method, url=url, **kwargs)
1747295662.2922766 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
1747295662.2923594 [ros_mission_website-5]     resp = self.send(prep, **send_kwargs)
1747295662.2924397 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
1747295662.2925467 [ros_mission_website-5]     r = adapter.send(request, **kwargs)
1747295662.2926233 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
1747295662.2926991 [ros_mission_website-5]     resp = conn.urlopen(
1747295662.2927744 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
1747295662.2928505 [ros_mission_website-5]     httplib_response = self._make_request(
1747295662.2929327 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
1747295662.2930279 [ros_mission_website-5]     self._validate_conn(conn)
1747295662.2931283 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
1747295662.2932169 [ros_mission_website-5]     conn.connect()
1747295662.2936189 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
1747295662.2937362 [ros_mission_website-5]     conn = self._new_conn()
1747295662.2938292 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
1747295662.2939141 [ros_mission_website-5]     conn = connection.create_connection(
1747295662.2939992 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
1747295662.2940867 [ros_mission_website-5]     sock.connect(sa)
1747295662.2941725 [ros_mission_website-5] KeyboardInterrupt
1747295662.2945898 [drone_handler-1]     handler = MAVConnection(ip, baud=baud, source_system=source_system, source_component=source_component, use_native=use_native)
1747295662.2947159 [drone_handler-1]   File "/usr/local/lib/python3.10/dist-packages/dronekit/mavlink.py", line 130, in __init__
1747295662.2948096 [drone_handler-1]     self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system, source_component=source_component)
1747295662.2948985 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 1823, in mavlink_connection
1747295662.2949860 [drone_handler-1]     return mavserial(device,
1747295662.2950721 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 971, in __init__
1747295662.2951574 [drone_handler-1]     raise e
1747295662.2952428 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 967, in __init__
1747295662.2953379 [drone_handler-1]     self.port = serial.Serial(self.device, 1200, timeout=0,
1747295662.2954183 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
1747295662.2955165 [drone_handler-1]     self.open()
1747295662.2955976 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
1747295662.2956779 [drone_handler-1]     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
1747295662.2957575 [drone_handler-1] serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295662.2958376 [drone_handler-1] 
1747295662.2959218 [drone_handler-1] During handling of the above exception, another exception occurred:
1747295662.2960072 [drone_handler-1] 
1747295662.2960865 [drone_handler-1] Traceback (most recent call last):
1747295662.2961659 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/drone_handler", line 33, in <module>
1747295662.2962458 [drone_handler-1]     sys.exit(load_entry_point('drone-hardware==0.0.0', 'console_scripts', 'drone_handler')())
1747295662.2963252 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 523, in main
1747295662.2964048 [drone_handler-1]     drone = DroneHandler()
1747295662.2964959 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 87, in __init__
1747295662.2965765 [drone_handler-1]     time.sleep(3)
1747295662.2966559 [drone_handler-1] KeyboardInterrupt
1747295662.3185356 [healthcheck-6] Traceback (most recent call last):
1747295662.3187134 [healthcheck-6]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/healthcheck.py", line 160, in main
1747295662.3191442 [healthcheck-6]     healthcheck_node.check_drone_handler_services()
1747295662.3192716 [healthcheck-6]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/healthcheck.py", line 65, in check_drone_handler_services
1747295662.3193822 [healthcheck-6]     rclpy.spin_until_future_complete(self, future, timeout_sec=5.0)
1747295662.3195202 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 253, in spin_until_future_complete
1747295662.3196199 [healthcheck-6]     executor.spin_until_future_complete(future, timeout_sec)
1747295662.3197179 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 320, in spin_until_future_complete
1747295662.3198113 [healthcheck-6]     self.spin_once_until_future_complete(future, timeout_left)
1747295662.3198986 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 758, in spin_once_until_future_complete
1747295662.3199844 [healthcheck-6]     self._spin_once_impl(timeout_sec)
1747295662.3200738 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
1747295662.3205781 [healthcheck-6]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
1747295662.3206842 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
1747295662.3207755 [healthcheck-6]     return next(self._cb_iter)
1747295662.3208752 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
1747295662.3209620 [healthcheck-6]     wait_set.wait(timeout_nsec)
1747295662.3210382 [healthcheck-6] KeyboardInterrupt
1747295662.3211231 [healthcheck-6] 
1747295662.3212082 [healthcheck-6] During handling of the above exception, another exception occurred:
1747295662.3213048 [healthcheck-6] 
1747295662.3214021 [healthcheck-6] Traceback (most recent call last):
1747295662.3216009 [healthcheck-6]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/healthcheck", line 33, in <module>
1747295662.3217022 [healthcheck-6]     sys.exit(load_entry_point('drone-hardware==0.0.0', 'console_scripts', 'healthcheck')())
1747295662.3217974 [healthcheck-6]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/healthcheck.py", line 168, in main
1747295662.3218846 [healthcheck-6]     rclpy.shutdown()
1747295662.3219984 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 130, in shutdown
1747295662.3220861 [healthcheck-6]     _shutdown(context=context)
1747295662.3221700 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
1747295662.3222501 [healthcheck-6]     return context.shutdown()
1747295662.3223567 [healthcheck-6]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
1747295662.3224492 [healthcheck-6]     self.__context.shutdown()
1747295662.3225713 [healthcheck-6] rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
1747295662.3564410 [ERROR] [images_recorder-3]: process has died [pid 11627, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/drone_camera/images_recorder --ros-args --params-file /tmp/launch_params_9hrwr7nq'].
1747295662.3701544 [ERROR] [aruco_node-4]: process has died [pid 11629, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/ros2_aruco/aruco_node --ros-args --params-file /tmp/launch_params_qvdsmhku'].
1747295662.3779967 [ERROR] [ros_mission_website-5]: process has died [pid 11631, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_web/lib/drone_web/ros_mission_website --ros-args --params-file /tmp/launch_params_czqn54ld'].
1747295662.3860917 [ERROR] [drone_handler-1]: process has died [pid 11623, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/drone_handler --ros-args --params-file /tmp/launch_params_uz5fofc3'].
1747295662.4903278 [ERROR] [healthcheck-6]: process has died [pid 11721, exit code 1, cmd '/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/healthcheck --ros-args --params-file /tmp/launch_params_vi11njck --params-file /tmp/launch_params_md7pm847'].
